# Generated by Django 5.2.5 on 2025-11-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(default='Tashkent', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='profrssion',
            field=models.CharField(default='worker', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='media/default.png', upload_to='media'),
        ),
    ]
