# Generated by Django 5.2.5 on 2025-11-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_location_product_profrssion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.EmailField(default='H2Jyj@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.IntegerField(default=998),
        ),
        migrations.AddField(
            model_name='product',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
    ]
