# Generated by Django 5.2.5 on 2025-11-18 23:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_product_number_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='profrssion',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='default'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='не указано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(default='default'),
        ),
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
